# -*- coding: utf-8 -*-
"""First-Open-Source-Rag-App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQtlFyPxfYqa0eBUUND8eD_6xqk_SNyW

# Build Your First RAG System with Free Open-Source LLM
[From youtube video](https://www.youtube.com/watch?v=bdW4meTVWS4) by [DataHeroes](https://www.youtube.com/@DataHeroes).

Learn how to build your first RAG system using the free open-source LLM model from Hugging Face with this easy tutorial. Perfect for beginners in Langchain technology!

We set up embeddings, store data in Faiss, and connect everything to a large language model (LLM) so it only answers from the data you provide. Download the materials (link below) to follow along, including a prompt engineering eBook and a starter file with the necessary data. By the end of this tutorial, you'll have a tour guide chatbot powered by real context—no random answers allowed!

Key Points in this Video:
Install and configure Hugging Face libraries
Set up Faiss for storing and retrieving data
Use LangChain for embeddings and context-based responses
Create a custom chatbot that answers only from your own data
Tips on prompt engineering to keep your model focused
"""

# Sample dataset with 30 facts about Berlin
documents = [
    "Berlin is the capital and largest city of Germany by both area and population.",
    "Berlin is known for its art scene and modern landmarks like the Berliner Philharmonie.",
    "The Berlin Wall, which divided the city from 1961 to 1989, was a significant Cold War symbol.",
    "Berlin has more bridges than Venice, with around 1,700 bridges.",
    "The city's Zoological Garden is the most visited zoo in Europe and one of the most popular worldwide.",
    "Berlin's Museum Island is a UNESCO World Heritage site with five world-renowned museums.",
    "The Reichstag building houses the German Bundestag (Federal Parliament).",
    "Berlin is famous for its diverse architecture, ranging from historic buildings to modern structures.",
    "The Berlin Marathon is one of the world's largest and most popular marathons.",
    "Berlin's public transportation system includes buses, trams, U-Bahn (subway), and S-Bahn (commuter train).",
    "The Brandenburg Gate is an iconic neoclassical monument in Berlin.",
    "Berlin has a thriving startup ecosystem and is considered a major tech hub in Europe.",
    "The city hosts the Berlinale, one of the most prestigious international film festivals.",
    "Berlin has more than 180 kilometers of navigable waterways.",
    "The East Side Gallery is an open-air gallery on a remaining section of the Berlin Wall.",
    "Berlin's Tempelhofer Feld, a former airport, is now a public park and recreational area.",
    "The TV Tower at Alexanderplatz offers panoramic views of the city.",
    "Berlin's Tiergarten is one of the largest urban parks in Germany.",
    "Checkpoint Charlie was a famous crossing point between East and West Berlin during the Cold War.",
    "Berlin is home to numerous theaters, including the Berliner Ensemble and the Volksbühne.",
    "The Berlin Philharmonic Orchestra is one of the most famous orchestras in the world.",
    "Berlin has a vibrant nightlife scene, with countless bars, clubs, and music venues.",
    "The Berlin Cathedral is a major Protestant church and a landmark of the city.",
    "Charlottenburg Palace is the largest palace in Berlin and a major tourist attraction.",
    "Berlin's Alexanderplatz is a large public square and transport hub in central Berlin.",
    "Berlin is known for its street art, with many murals and graffiti artworks around the city.",
    "The Gendarmenmarkt is a historic square in Berlin featuring the Konzerthaus, French Cathedral, and German Cathedral.",
    "Berlin has a strong coffee culture, with numerous cafés throughout the city.",
    "The Berlin TV Tower is the tallest structure in Germany, standing at 368 meters.",
    "Berlin's KaDeWe is one of the largest and most famous department stores in Europe.",
    "The Berlin U-Bahn network has 10 lines and serves 173 stations.",
    "Berlin has a population of over 3.6 million people.",
    "The city of Berlin covers an area of 891.8 square kilometers.",
    "Berlin has a temperate seasonal climate.",
    "The Berlin International Film Festival, also known as the Berlinale, is one of the world's leading film festivals.",
    "Berlin is home to the Humboldt University, founded in 1810.",
    "The Berlin Hauptbahnhof is the largest train station in Europe.",
    "Berlin's Tegel Airport closed in 2020, and operations moved to Berlin Brandenburg Airport.",
    "The Spree River runs through the center of Berlin.",
    "Berlin is twinned with Los Angeles, California, USA.",
    "The Berlin Botanical Garden is one of the largest and most important botanical gardens in the world.",
    "Berlin has over 2,500 public parks and gardens.",
    "The Victory Column (Siegessäule) is a famous monument in Berlin.",
    "Berlin's Olympic Stadium was built for the 1936 Summer Olympics.",
    "The Berlin State Library is one of the largest libraries in Europe.",
    "The Berlin Dungeon is a popular tourist attraction that offers a spooky look at the city's history.",
    "Berlin's economy is based on high-tech industries and the service sector.",
    "Berlin is a major center for culture, politics, media, and science.",
    "The Berlin Wall Memorial commemorates the division of Berlin and the victims of the Wall.",
    "The city has a large Turkish community, with many residents of Turkish descent.",
    "Berlin's Mauerpark is a popular park known for its flea market and outdoor karaoke sessions.",
    "The Berlin Zoological Garden is the oldest zoo in Germany, opened in 1844.",
    "Berlin is known for its diverse culinary scene, including many vegan and vegetarian restaurants.",
    "The Berliner Dom is a baroque-style cathedral located on Museum Island.",
    "The DDR Museum in Berlin offers interactive exhibits about life in East Germany.",
    "Berlin has a strong cycling culture, with many dedicated bike lanes and bike-sharing programs.",
    "Berlin's Tempodrom is a multi-purpose event venue known for its unique architecture.",
    "The Berlinische Galerie is a museum of modern art, photography, and architecture.",
    "Berlin's Volkspark Friedrichshain is the oldest public park in the city, established in 1848.",
    "The Hackesche Höfe is a complex of interconnected courtyards in Berlin's Mitte district, known for its vibrant nightlife and art scene.",
    "Berlin's International Congress Center (ICC) is one of the largest conference centers in the world.",
    "Berlin people do not get a long with people from Fremont",
    "There are French people in Berlin too, they only eat hotdogs."
]

from google.colab import userdata
hf_key = userdata.get('HF_TOKEN')

import os
os.environ['HUGGINGFACEHUB_API_TOKEN'] = hf_key

!pip install faiss-cpu langchain-huggingface sentence-transformers langchain_community -q

# Import libraries
from langchain_huggingface import HuggingFaceEmbeddings, ChatHuggingFace, HuggingFaceEndpoint
from langchain.vectorstores import FAISS
from langchain.docstore.document import Document
from langchain_core.messages import HumanMessage, SystemMessage
from IPython.display import display, Markdown

"""# Embeddings

After installing the correct version of `requests`, you can re-run the `!pip install faiss-cpu langchain-huggingface sentence-transformers langchain_community -q` cell.
"""

# wrap in a document
docs = [Document(page_content = text) for text in documents]

# use the embedding model
embedding_model = HuggingFaceEmbeddings(model_name = "sentence-transformers/all-miniLM-L6-v2")

# create a FAISS db
faiss_db = FAISS.from_documents(docs, embedding_model)

"""# Build the Retreival"""

# Define a function for retreival
def retrieve_docs(query, k = 5):
  docs_faiss = faiss_db.similarity_search(query, k)
  return docs_faiss

# Test the retreival system
query = "What is the capital of Germany?"
docs_faiss = retrieve_docs(query)
docs_faiss

"""# Build the Generative System"""

# Load a compatible model
llm = HuggingFaceEndpoint(repo_id = "mistralai/Mistral-7B-Instruct-v0.2", task = "text-generation")
chat_model = ChatHuggingFace(llm = llm)

# Define a function to ask the LLM
def ask(query):
  messages = [
      SystemMessage(content = "You are a tour guide."),
      HumanMessage(content = query)
  ]
  response = chat_model.invoke(messages)
  return display(Markdown(response.content))

# Apply the function
query = "What is the capital of Germany?"
response = ask(query)
print(response)

# Define a function to ask the LLM, Limit scope to Context ONLY answers.
def ask2(query, context):
  messages = [
      SystemMessage(content = "You are a tour guide. Answer question only available in {context}. If you don't have the information, just say you don't know."),
      HumanMessage(content = f"""
      Answer the {query} based on the {context}
      """)
  ]
  response = chat_model.invoke(messages)
  return display(Markdown(response.content))

# Define the function for RAG
def ask_rag(query):
  context = retrieve_docs(query)
  ask2(query, context)
  return ask2(query, context)

# Test the ask_rag function
query = "Are there any French people in Berlin?"
response = ask_rag(query)
print(response)